# Generated by Django 3.1.6 on 2021-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='length',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='width',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999999999.99.'}}, help_text='Maximum 99999999.99', max_digits=12, verbose_name='Product price'),
        ),
    ]
