"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from pathlib import Path
import os

if os.name == 'nt':
    VENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(
        VENV_BASE, 'Lib\\site-packages\\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(
        VENV_BASE, 'Lib\\site-packages\\osgeo\\data\\proj') + ';' + os.environ['PATH']

"""# Build paths inside the project like this: BASE_DIR / 'subdir'."""
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&4c2yowj06vmd_=o9$g8qc-7)5p4*%!(21%d$1lxa-1kh9a89b'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = int(os.environ.get('DEBUG',default=1))
ALLOWED_HOSTS = ['*']

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

"""
# Application definition
"""
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    # My own applications
    'apps.account.apps.AccountConfig',
    'apps.product.apps.ProductConfig',
    # 'apps.pickup.apps.PickUpConfig',
    # 'apps.search.apps.SearchConfig',
    # 'apps.auction.apps.AuctionConfig',
    # 'apps.messenger.apps.MessengerConfig',
    # 'apps.trade.apps.TradeConfig',
    # 'apps.shipping.apps.ShippingConfig',
    # 'apps.utils.apps.UtilsConfig',
    
    # Third Party Application
    'channels',
    'django_extensions',
    'leaflet',
    'mapwidgets',
    'drf_yasg',
    'rest_framework.authtoken',
    'rest_framework',
    'mptt',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'
"""
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'tradeit',
        'USER': 'postgres',
        'PASSWORD': '8302',
        'HOST': "winhost",
        'PORT': 5432,
    },
}


"""
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


"""
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
"""
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# GDAL

os.environ['PATH'] = os.path.join(
    BASE_DIR, r'venv\Lib\site-packages\osgeo') + ';' + os.environ['PATH']

os.environ['PROJ_LIB'] = os.path.join(
    BASE_DIR, r'venv\Lib\site-packages\osgeo\data\proj') + ';' + os.environ['PATH']

# GDAL_LIBRARY_PATH = os.path.join(
#     BASE_DIR, r'venv\Lib\site-packages\osgeo\gdal302.dll')


"""
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
"""
STATIC_URL = '/static/'
# Media Storage
MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'

# User model customatation

AUTH_USER_MODEL = 'account.User'

# Email settings

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'letsteamovie@gmail.com'
EMAIL_HOST_PASSWORD = '8302D10C0C'

# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')


""" Rest Framework settings """

REST_FRAMEWORK = {
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 35,
    # 'NON_FIELD_ERRORS_KEY': 'error',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}


"""
Map Settings
"""
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (36.753769, 3.058756),
    'DEFAULT_ZOOM': 15,
    'MAX_ZOOM': 20,
    'MIN_ZOOM': 5,

}

# MAP_WIDGETS = {
#     "GOOGLE_MAP_API_KEY": os.environ.get('GOOGLE_MAP_API_KEY')
# }
