# Generated by Django 3.1.6 on 2021-09-21 13:29

import apps.account.models
import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Username')),
                ('phone', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male'), ('none', 'prefered not to say')], default='none', max_length=60, null=True)),
                ('birthdate', models.DateField(null=True, verbose_name='date of birth')),
                ('started_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, default='defaults/avatar/none/none.jpg', null=True, storage=apps.account.models.OverwriteStorage(), upload_to=apps.account.models.uploadmodel_file_upload_to)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('zipcode', models.CharField(max_length=150, null=True)),
                ('location_points', django.contrib.gis.db.models.fields.PointField(max_length=40, null=True, srid=4326)),
                ('radius', models.IntegerField(default=20, help_text='in kilometers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trades', models.IntegerField(default=0)),
                ('bought', models.IntegerField(default=0)),
                ('selled', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('jp', 'Japanese'), ('ch', 'Chinese')], default='en', max_length=7)),
                ('payment_verified', models.BooleanField(default=False)),
                ('confirmed_phone', models.BooleanField(default=False)),
                ('confirmed_facebook', models.BooleanField(default=False)),
                ('confirmed_email', models.BooleanField(default=False)),
                ('is_trusted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(related_name='followers_profile', to='account.Profile')),
                ('following', models.ManyToManyField(related_name='followings_profile', to='account.Profile')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('zipcode', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField()),
                ('last_login', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IP addresses',
                'ordering': ('-last_login',),
                'unique_together': {('user', 'IPAddress')},
            },
        ),
    ]
